In [1]:
import numpy as np

In [6]:
x = np.array([40,57,67,9.8,"A"])
print(x)
print(type(x))
print(x.dtype)

['40' '57' '67' '9.8' 'A']
<class 'numpy.ndarray'>
<U32


In [7]:
# create a 2D array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [9]:
# Reshaping an aray
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [11]:
# Creating an array with arange()
c = np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [12]:
# use of around()
d = np.array([1.347,3.10987,4.91236])
print(np.around(np.sqrt(d),2))

[1.16 1.76 2.22]


In [13]:
# Use astype() to convert
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
print(a1)

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


In [14]:
a1_copy1 = a1.astype(str)
print(a1_copy1)


[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


In [15]:
# mathematical operation on rows
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [16]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [17]:
# find the nean values along row and col
print(a2)
print(np.mean(a2, axis = 1))
print(np.mean(a2, axis =0))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [18]:
# matrix operations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [22]:
# define two matrices and multiply them
A = np.array([[1,2], [3,4]])
B = np.array([[4,5],[7,6]])

c = np.matmul(A, B)
print(c)

[[18 17]
 [40 39]]


In [23]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[4 7]
 [5 6]]


In [24]:
# accessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [27]:
# slicing of array
a4[1:3,0:2]

array([[7, 2],
       [9, 1]])